sections:
  genomics:
    deadlines:
      '1':
        Wed:
          date: 2026/05/20 12:00pm 
          content: h1g
        Fri:
          date: 2026/05/22 12:00pm
          content: h2g
      '2':
        Wed:
          date: 2026/05/27 12:00pm 
          content: h3g
        Fri:
          date: 2026/05/29 12:00pm 
          content: h4g
    dates:
      firstMonday: 2026/05/18
      numWeeks: 2
    types:
      default:
        className: lesson
      holiday:
        className: holiday
  programming:
    deadlines:
      '1':
        Fri:
          date: 2026/07/03 12:00pm
          content: h1r
      '2':
        Fri:
          date: 2026/07/10 12:00pm 
          content: h2r
      '3':
        Fri:
          date: 2026/07/17 12:00pm
          content: h3r
      '4':
        Fri:
          date: 2026/07/24 12:00pm 
          content: h4r
    dates:
      firstMonday: 2026/06/29
      numWeeks: 5
    types:
      default:
        className: lesson
      holiday:
        className: holiday
